-- bnabd - struktura bazy danych (PostgreSQL).
-- Skrypt pokazowy: w praktyce schemat tworzy Hibernate (ddl-auto=update),
-- a dane przykladowe sieje DatabaseSeedService przy starcie backendu.
-- Uruchomienie reczne: psql -U bnabd -d bnabd -f docs/bnabd_init.sql

DROP TABLE IF EXISTS reviews       CASCADE;
DROP TABLE IF EXISTS reservations  CASCADE;
DROP TABLE IF EXISTS rooms         CASCADE;
DROP TABLE IF EXISTS shelters      CASCADE;
DROP TABLE IF EXISTS users         CASCADE;

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    login         VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_users        PRIMARY KEY (id),
    CONSTRAINT uq_users_login  UNIQUE (login),
    CONSTRAINT uq_users_email  UNIQUE (email),
    CONSTRAINT ck_users_role   CHECK (role IN ('USER', 'HOST', 'ADMIN'))
);

CREATE TABLE shelters (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    owner_id               BIGINT,
    name                   VARCHAR(255)  NOT NULL,
    description            VARCHAR(1200),
    location               VARCHAR(255)  NOT NULL,
    phone                  VARCHAR(255),
    email                  VARCHAR(255),
    image_url              VARCHAR(1000),
    rating                 FLOAT8 NOT NULL DEFAULT 0,
    board_breakfast_price  NUMERIC(38,2),
    board_half_board_price NUMERIC(38,2),
    board_full_board_price NUMERIC(38,2),
    CONSTRAINT pk_shelters        PRIMARY KEY (id),
    CONSTRAINT fk_shelters_owner  FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_shelters_rating CHECK (rating >= 0 AND rating <= 5),
    CONSTRAINT ck_shelters_board_prices CHECK (
        (board_breakfast_price  IS NULL OR board_breakfast_price  >= 0) AND
        (board_half_board_price IS NULL OR board_half_board_price >= 0) AND
        (board_full_board_price IS NULL OR board_full_board_price >= 0)
    )
);

CREATE TABLE rooms (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shelter_id      BIGINT        NOT NULL,
    name            VARCHAR(255)  NOT NULL,
    capacity        INTEGER       NOT NULL,
    room_type       VARCHAR(255),
    price_per_night NUMERIC(10,2) NOT NULL,
    CONSTRAINT pk_rooms          PRIMARY KEY (id),
    CONSTRAINT fk_rooms_shelter  FOREIGN KEY (shelter_id) REFERENCES shelters (id),
    CONSTRAINT ck_rooms_type     CHECK (room_type IS NULL OR room_type IN ('WHOLE', 'SHARED')),
    CONSTRAINT ck_rooms_capacity CHECK (capacity > 0),
    CONSTRAINT ck_rooms_price    CHECK (price_per_night >= 0)
);

CREATE TABLE reservations (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT        NOT NULL,
    room_id     BIGINT        NOT NULL,
    start_date  DATE          NOT NULL,
    end_date    DATE          NOT NULL,
    guest_count INTEGER       NOT NULL,
    total_price NUMERIC(10,2) NOT NULL,
    status      VARCHAR(255)  NOT NULL,
    board_type  VARCHAR(255),
    guest_name  VARCHAR(255),
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_reservations        PRIMARY KEY (id),
    CONSTRAINT fk_reservations_user   FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_reservations_room   FOREIGN KEY (room_id) REFERENCES rooms (id),
    CONSTRAINT ck_reservations_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT ck_reservations_dates  CHECK (end_date > start_date),
    CONSTRAINT ck_reservations_guests CHECK (guest_count > 0),
    CONSTRAINT ck_reservations_price  CHECK (total_price >= 0)
);

CREATE TABLE reviews (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id    BIGINT  NOT NULL,
    shelter_id BIGINT  NOT NULL,
    rating     INTEGER NOT NULL,
    comment    VARCHAR(1000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_reviews         PRIMARY KEY (id),
    CONSTRAINT fk_reviews_user    FOREIGN KEY (user_id)    REFERENCES users (id),
    CONSTRAINT fk_reviews_shelter FOREIGN KEY (shelter_id) REFERENCES shelters (id),
    CONSTRAINT ck_reviews_rating  CHECK (rating BETWEEN 1 AND 5)
);
